image: cirrusci/flutter:stable


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - flutter pub get
    - flutter pub run build_runner build
    - flutter build web
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - flutter pub get
    - flutter pub run build_runner build
    - flutter build web
    - mv build/web public
    - chmod 777 -R public
  artifacts:
    paths:
      - public