# The Docker image that will be used to build your app
image: ghcr.io/cirruslabs/flutter:beta
# Functions that should be executed before the build script is run
before_script:
  - flutter doctor
  - flutter config --enable-web
  - sudo apt-get update
  - sudo apt-get install -y chromium-browser
  - sudo rm -rf /var/lib/apt/lists/*
  - flutter clean
  - flutter pub get
pages:
  script:
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build web --release --base-href /stelaris-ui/
    - mv build/web public
    - chmod 777 -R public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    # - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
