image: ${HTL_NEXUS_PROXY}/cirruslabs/flutter:latest
variables:
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker
  BUILDAH_ISOLATION: chroot
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CACHE_COMPRESSION_LEVEL: "fastest"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  FF_USE_FASTZIP: 1
cache:
  paths:
    - $CI_PROJECT_DIR/.pub-cache/
pages:
  stage: build
  script:
  - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
  - export PATH="$PATH":"$PUB_CACHE/bin"
  - flutter config --enable-web
  - sudo apt-get update
  - sudo apt-get install -y chromium-browser
  - sudo rm -rf /var/lib/apt/lists/*
  - flutter doctor
  - flutter pub get
  - flutter clean
  - flutter pub run build_runner build --delete-conflicting-outputs
  - flutter build web --release --base-href /
  - mv build/web public
  - chmod 777 -R public
  artifacts:
    paths:
    # The folder that contains the files to be exposed at the Page URL
    - public
  only:
    - tags
pre-container:
  stage: build
  tags:
    - saas-linux-medium-amd64
  script:
  - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
  - export PATH="$PATH":"$PUB_CACHE/bin"
  - flutter config --enable-web
  - sudo apt-get update
  - sudo apt-get install -y chromium-browser
  - sudo rm -rf /var/lib/apt/lists/*
  - flutter doctor
  - flutter pub get
  - cp $ENV_PROD lib/env/environment.dart
  - flutter clean
  - flutter pub run build_runner build --delete-conflicting-outputs
  - flutter build web --release --base-href /
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  only:
    - tags
container:
  image: "${HTL_NEXUS_PROXY}/buildah/stable:latest"
  tags:
    - saas-linux-medium-amd64
  dependencies:
    - "pre-container"
  needs:
    - "pre-container"
  stage: build
  cache: {}
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
    - buildah push $IMAGE_TAG
    - buildah push $CI_REGISTRY_IMAGE:latest
  only:
    - tags