name: stelaris_ui
description: UI for stelaris

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  freezed_annotation: ^2.4.3
  dio: ^5.5.0+1
  dio_cache_interceptor: ^3.5.0
  localstorage: ^5.0.0
  async_redux: ^23.0.2
  nil: ^1.1.1
  intl: ^0.19.0
  json_annotation: 4.9.0
  expandable: ^5.0.1
  web: ^0.5.1

dependency_overrides:
  analyzer: ^6.5.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true