name: stelaris_ui
description: UI for stelaris

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^4.3.0
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  localstorage: ^4.0.0+1
  async_redux: 17.0.1
  data_table_2: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true


