name: stelaris
description: UI for Stelaris

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^15.2.3
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  localstorage: ^6.0.0
  async_redux: ^25.4.0
  nil: ^1.1.1
  intl: ^0.20.2
  json_annotation: 4.9.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
