name: Stelaris
description: UI for Stelaris

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.7.2
  freezed_annotation: ^2.4.4
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  localstorage: ^5.0.0
  async_redux: ^24.0.7
  nil: ^1.1.1
  intl: ^0.19.0
  json_annotation: 4.9.0
  expandable: ^5.0.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  generate: true
