name: stelaris_ui
description: UI for stelaris

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.4
  freezed_annotation: ^2.4.1
  dio: ^5.4.2+1
  dio_cache_interceptor: ^3.5.0
  localstorage: ^4.0.1+4
  async_redux: ^21.4.0
  nil: ^1.1.1
  intl: ^0.18.1
  json_annotation: 4.9.0
  expandable: ^5.0.1
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true