import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';

/// Represents an RFC 9457 Problem Detail error response from the backend.
@immutable
class ProblemDetail {
  const ProblemDetail({
    required this.title,
    required this.status,
    this.type,
    this.detail = '',
    this.instance,
    this.code,
    this.traceId,
    this.errors = const [],
  });

  /// A URI reference that identifies the problem type.
  final String? type;

  /// A short, human-readable summary of the problem type.
  final String title;

  /// The HTTP status code generated by the origin server for this occurrence.
  final int status;

  /// A human-readable explanation specific to this occurrence of the problem.
  final String detail;

  /// A URI reference that identifies the specific occurrence of the problem.
  final String? instance;

  /// A stable, machine-readable error code (e.g. `RESOURCE_NOT_FOUND`, `VALIDATION_FAILED`).
  final String? code;

  /// A unique trace/correlation identifier for support.
  final String? traceId;

  /// Optional list of field-specific validation errors.
  final List<ProblemValidationError> errors;

  /// Returns the best human-readable message to display in the UI.
  String get displayMessage {
    if (detail.isNotEmpty) {
      return detail;
    }
    return title;
  }

  /// Returns `true` if this problem represents an input or validation warning (400, 409, or VALIDATION_FAILED).
  bool get isValidationError =>
      status == 400 ||
      status == 409 ||
      code == 'VALIDATION_FAILED' ||
      code == 'INVALID_VALUE' ||
      errors.isNotEmpty;

  factory ProblemDetail.fromJson(Map<String, dynamic> json) {
    final rawErrors = json['errors'];
    final parsedErrors = <ProblemValidationError>[];

    if (rawErrors is List) {
      for (final e in rawErrors) {
        if (e is Map<String, dynamic>) {
          parsedErrors.add(ProblemValidationError.fromJson(e));
        }
      }
    }

    return ProblemDetail(
      type: json['type'] as String?,
      title: (json['title'] as String?) ?? 'Error',
      status: (json['status'] as num?)?.toInt() ?? 500,
      detail: (json['detail'] as String?) ?? '',
      instance: json['instance'] as String?,
      code: json['code'] as String?,
      traceId: json['traceId'] as String?,
      errors: List.unmodifiable(parsedErrors),
    );
  }

  Map<String, dynamic> toJson() => {
    if (type != null) 'type': type,
    'title': title,
    'status': status,
    if (detail.isNotEmpty) 'detail': detail,
    if (instance != null) 'instance': instance,
    if (code != null) 'code': code,
    if (traceId != null) 'traceId': traceId,
    if (errors.isNotEmpty) 'errors': errors.map((e) => e.toJson()).toList(),
  };

  /// Parses a [ProblemDetail] from a [DioException].
  ///
  /// If the backend returned an RFC 9457 JSON body, it is parsed directly.
  /// Otherwise, a fallback [ProblemDetail] is created based on the Dio error type.
  factory ProblemDetail.fromDioException(DioException dioException) {
    final responseData = dioException.response?.data;

    if (responseData is Map<String, dynamic>) {
      try {
        return ProblemDetail.fromJson(responseData);
      } catch (_) {
        // Fall back to Dio error info if JSON didn't match
      }
    } else if (responseData is String && responseData.trim().startsWith('{')) {
      try {
        final decoded = jsonDecode(responseData);
        if (decoded is Map<String, dynamic>) {
          return ProblemDetail.fromJson(decoded);
        }
      } catch (_) {
        // Fall back
      }
    }

    // Network / timeout fallbacks
    switch (dioException.type) {
      case DioExceptionType.connectionTimeout:
      case DioExceptionType.sendTimeout:
      case DioExceptionType.receiveTimeout:
        return const ProblemDetail(
          title: 'Connection Timeout',
          status: 408,
          detail: 'The request timed out. Please check your connection.',
          code: 'CONNECTION_TIMEOUT',
        );

      case DioExceptionType.connectionError:
        return const ProblemDetail(
          title: 'Connection Error',
          status: 503,
          detail: 'Unable to connect to the server. Please check your network or server status.',
          code: 'CONNECTION_ERROR',
        );

      default:
        final statusCode = dioException.response?.statusCode ?? 500;
        final message = dioException.message ?? 'An unexpected error occurred.';
        return ProblemDetail(
          title: 'Error ($statusCode)',
          status: statusCode,
          detail: message,
          code: 'UNKNOWN_ERROR',
        );
    }
  }

  @override
  String toString() => 'ProblemDetail(status: $status, title: "$title", detail: "$detail", code: $code)';
}

/// Represents an individual field validation error in RFC 9457 responses.
@immutable
class ProblemValidationError {
  const ProblemValidationError({
    required this.field,
    required this.message,
    this.code,
  });

  final String field;
  final String? code;
  final String message;

  factory ProblemValidationError.fromJson(Map<String, dynamic> json) {
    return ProblemValidationError(
      field: (json['field'] as String?) ?? '',
      code: json['code'] as String?,
      message: (json['message'] as String?) ?? '',
    );
  }

  Map<String, dynamic> toJson() => {
    'field': field,
    if (code != null) 'code': code,
    'message': message,
  };

  @override
  String toString() => 'ProblemValidationError(field: $field, code: $code, message: $message)';
}
