// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint, type=warning, deprecated_member_use, deprecated_member_use_from_same_package
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'problem_detail.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
T _$identity<T>(T value) => value;
/// @nodoc
mixin _$ProblemDetail {

/// A short, human-readable summary of the problem type.
 String get title;/// The HTTP status code generated by the origin server for this occurrence.
 int get status;/// A URI reference that identifies the problem type.
 String? get type;/// A human-readable explanation specific to this occurrence of the problem.
 String get detail;/// A URI reference that identifies the specific occurrence of the problem.
 String? get instance;/// A stable, machine-readable error code (e.g. `RESOURCE_NOT_FOUND`, `VALIDATION_FAILED`).
 String? get code;/// A unique trace/correlation identifier for support.
 String? get traceId;/// Optional list of field-specific validation errors.
 List<ProblemValidationError> get errors;
/// Create a copy of ProblemDetail
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$ProblemDetailCopyWith<ProblemDetail> get copyWith => _$ProblemDetailCopyWithImpl<ProblemDetail>(this as ProblemDetail, _$identity);



@override
bool operator ==(Object other) {
  final _this = this as ProblemDetail;
  return identical(this, other) || (other.runtimeType == runtimeType&&other is ProblemDetail&&(identical(other.title, _this.title) || other.title == _this.title)&&(identical(other.status, _this.status) || other.status == _this.status)&&(identical(other.type, _this.type) || other.type == _this.type)&&(identical(other.detail, _this.detail) || other.detail == _this.detail)&&(identical(other.instance, _this.instance) || other.instance == _this.instance)&&(identical(other.code, _this.code) || other.code == _this.code)&&(identical(other.traceId, _this.traceId) || other.traceId == _this.traceId)&&const DeepCollectionEquality().equals(other.errors, _this.errors));
}


@override
int get hashCode {
  final _this = this as ProblemDetail;
  return Object.hash(runtimeType,_this.title,_this.status,_this.type,_this.detail,_this.instance,_this.code,_this.traceId,const DeepCollectionEquality().hash(_this.errors));
}

@override
String toString() {
  final _this = this as ProblemDetail;
  return 'ProblemDetail(title: ${_this.title}, status: ${_this.status}, type: ${_this.type}, detail: ${_this.detail}, instance: ${_this.instance}, code: ${_this.code}, traceId: ${_this.traceId}, errors: ${_this.errors})';
}


}

/// @nodoc
abstract mixin class $ProblemDetailCopyWith<$Res>  {
  factory $ProblemDetailCopyWith(ProblemDetail value, $Res Function(ProblemDetail) _then) = _$ProblemDetailCopyWithImpl;
@useResult
$Res call({
 String title, int status, String? type, String detail, String? instance, String? code, String? traceId, List<ProblemValidationError> errors
});




}
/// @nodoc
class _$ProblemDetailCopyWithImpl<$Res>
    implements $ProblemDetailCopyWith<$Res> {
  _$ProblemDetailCopyWithImpl(this._self, this._then);

  final ProblemDetail _self;
  final $Res Function(ProblemDetail) _then;

/// Create a copy of ProblemDetail
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? title = null,Object? status = null,Object? type = freezed,Object? detail = null,Object? instance = freezed,Object? code = freezed,Object? traceId = freezed,Object? errors = null,}) {
  return _then(ProblemDetail(
title: null == title ? _self.title : title // ignore: cast_nullable_to_non_nullable
as String,status: null == status ? _self.status : status // ignore: cast_nullable_to_non_nullable
as int,type: freezed == type ? _self.type : type // ignore: cast_nullable_to_non_nullable
as String?,detail: null == detail ? _self.detail : detail // ignore: cast_nullable_to_non_nullable
as String,instance: freezed == instance ? _self.instance : instance // ignore: cast_nullable_to_non_nullable
as String?,code: freezed == code ? _self.code : code // ignore: cast_nullable_to_non_nullable
as String?,traceId: freezed == traceId ? _self.traceId : traceId // ignore: cast_nullable_to_non_nullable
as String?,errors: null == errors ? _self.errors : errors // ignore: cast_nullable_to_non_nullable
as List<ProblemValidationError>,
  ));
}

}


/// Adds pattern-matching-related methods to [ProblemDetail].
extension ProblemDetailPatterns on ProblemDetail {
/// A variant of `map` that fallback to returning `orElse`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeMap<TResult extends Object?>(TResult Function( _ProblemDetail value)?  $default,{required TResult orElse(),}){
final _that = this;
switch (_that) {
case _ProblemDetail() when $default != null:
return $default(_that);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// Callbacks receives the raw object, upcasted.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case final Subclass2 value:
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult map<TResult extends Object?>(TResult Function( _ProblemDetail value)  $default,){
final _that = this;
switch (_that) {
case _ProblemDetail():
return $default(_that);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `map` that fallback to returning `null`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? mapOrNull<TResult extends Object?>(TResult? Function( _ProblemDetail value)?  $default,){
final _that = this;
switch (_that) {
case _ProblemDetail() when $default != null:
return $default(_that);case _:
  return null;

}
}
/// A variant of `when` that fallback to an `orElse` callback.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeWhen<TResult extends Object?>(TResult Function( String title,  int status,  String? type,  String detail,  String? instance,  String? code,  String? traceId,  List<ProblemValidationError> errors)?  $default,{required TResult orElse(),}) {final _that = this;
switch (_that) {
case _ProblemDetail() when $default != null:
return $default(_that.title,_that.status,_that.type,_that.detail,_that.instance,_that.code,_that.traceId,_that.errors);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// As opposed to `map`, this offers destructuring.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case Subclass2(:final field2):
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult when<TResult extends Object?>(TResult Function( String title,  int status,  String? type,  String detail,  String? instance,  String? code,  String? traceId,  List<ProblemValidationError> errors)  $default,) {final _that = this;
switch (_that) {
case _ProblemDetail():
return $default(_that.title,_that.status,_that.type,_that.detail,_that.instance,_that.code,_that.traceId,_that.errors);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `when` that fallback to returning `null`
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? whenOrNull<TResult extends Object?>(TResult? Function( String title,  int status,  String? type,  String detail,  String? instance,  String? code,  String? traceId,  List<ProblemValidationError> errors)?  $default,) {final _that = this;
switch (_that) {
case _ProblemDetail() when $default != null:
return $default(_that.title,_that.status,_that.type,_that.detail,_that.instance,_that.code,_that.traceId,_that.errors);case _:
  return null;

}
}

}

/// @nodoc


class _ProblemDetail extends ProblemDetail {
  const _ProblemDetail({required this.title, required this.status, this.type, this.detail = '', this.instance, this.code, this.traceId,  List<ProblemValidationError> errors = const []}): _errors = errors,super._();
  

/// A short, human-readable summary of the problem type.
@override final  String title;
/// The HTTP status code generated by the origin server for this occurrence.
@override final  int status;
/// A URI reference that identifies the problem type.
@override final  String? type;
/// A human-readable explanation specific to this occurrence of the problem.
@override@JsonKey() final  String detail;
/// A URI reference that identifies the specific occurrence of the problem.
@override final  String? instance;
/// A stable, machine-readable error code (e.g. `RESOURCE_NOT_FOUND`, `VALIDATION_FAILED`).
@override final  String? code;
/// A unique trace/correlation identifier for support.
@override final  String? traceId;
/// Optional list of field-specific validation errors.
 final  List<ProblemValidationError> _errors;
/// Optional list of field-specific validation errors.
@override@JsonKey() List<ProblemValidationError> get errors {
  if (_errors is EqualUnmodifiableListView) return _errors;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(_errors);
}


/// Create a copy of ProblemDetail
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$ProblemDetailCopyWith<_ProblemDetail> get copyWith => __$ProblemDetailCopyWithImpl<_ProblemDetail>(this, _$identity);



@override
bool operator ==(Object other) {
    return identical(this, other) || (other.runtimeType == runtimeType&&other is _ProblemDetail&&(identical(other.title, title) || other.title == title)&&(identical(other.status, status) || other.status == status)&&(identical(other.type, type) || other.type == type)&&(identical(other.detail, detail) || other.detail == detail)&&(identical(other.instance, instance) || other.instance == instance)&&(identical(other.code, code) || other.code == code)&&(identical(other.traceId, traceId) || other.traceId == traceId)&&const DeepCollectionEquality().equals(other.errors, _errors));
}


@override
int get hashCode {
    return Object.hash(runtimeType,title,status,type,detail,instance,code,traceId,const DeepCollectionEquality().hash(_errors));
}

@override
String toString() {
    return 'ProblemDetail(title: $title, status: $status, type: $type, detail: $detail, instance: $instance, code: $code, traceId: $traceId, errors: $errors)';
}


}

/// @nodoc
abstract mixin class _$ProblemDetailCopyWith<$Res> implements $ProblemDetailCopyWith<$Res> {
  factory _$ProblemDetailCopyWith(_ProblemDetail value, $Res Function(_ProblemDetail) _then) = __$ProblemDetailCopyWithImpl;
@override @useResult
$Res call({
 String title, int status, String? type, String detail, String? instance, String? code, String? traceId, List<ProblemValidationError> errors
});




}
/// @nodoc
class __$ProblemDetailCopyWithImpl<$Res>
    implements _$ProblemDetailCopyWith<$Res> {
  __$ProblemDetailCopyWithImpl(this._self, this._then);

  final _ProblemDetail _self;
  final $Res Function(_ProblemDetail) _then;

/// Create a copy of ProblemDetail
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? title = null,Object? status = null,Object? type = freezed,Object? detail = null,Object? instance = freezed,Object? code = freezed,Object? traceId = freezed,Object? errors = null,}) {
  return _then(_ProblemDetail(
title: null == title ? _self.title : title // ignore: cast_nullable_to_non_nullable
as String,status: null == status ? _self.status : status // ignore: cast_nullable_to_non_nullable
as int,type: freezed == type ? _self.type : type // ignore: cast_nullable_to_non_nullable
as String?,detail: null == detail ? _self.detail : detail // ignore: cast_nullable_to_non_nullable
as String,instance: freezed == instance ? _self.instance : instance // ignore: cast_nullable_to_non_nullable
as String?,code: freezed == code ? _self.code : code // ignore: cast_nullable_to_non_nullable
as String?,traceId: freezed == traceId ? _self.traceId : traceId // ignore: cast_nullable_to_non_nullable
as String?,errors: null == errors ? _self._errors : errors // ignore: cast_nullable_to_non_nullable
as List<ProblemValidationError>,
  ));
}


}

/// @nodoc
mixin _$ProblemValidationError {

 String get field; String get message; String? get code;
/// Create a copy of ProblemValidationError
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$ProblemValidationErrorCopyWith<ProblemValidationError> get copyWith => _$ProblemValidationErrorCopyWithImpl<ProblemValidationError>(this as ProblemValidationError, _$identity);



@override
bool operator ==(Object other) {
  final _this = this as ProblemValidationError;
  return identical(this, other) || (other.runtimeType == runtimeType&&other is ProblemValidationError&&(identical(other.field, _this.field) || other.field == _this.field)&&(identical(other.message, _this.message) || other.message == _this.message)&&(identical(other.code, _this.code) || other.code == _this.code));
}


@override
int get hashCode {
  final _this = this as ProblemValidationError;
  return Object.hash(runtimeType,_this.field,_this.message,_this.code);
}

@override
String toString() {
  final _this = this as ProblemValidationError;
  return 'ProblemValidationError(field: ${_this.field}, message: ${_this.message}, code: ${_this.code})';
}


}

/// @nodoc
abstract mixin class $ProblemValidationErrorCopyWith<$Res>  {
  factory $ProblemValidationErrorCopyWith(ProblemValidationError value, $Res Function(ProblemValidationError) _then) = _$ProblemValidationErrorCopyWithImpl;
@useResult
$Res call({
 String field, String message, String? code
});




}
/// @nodoc
class _$ProblemValidationErrorCopyWithImpl<$Res>
    implements $ProblemValidationErrorCopyWith<$Res> {
  _$ProblemValidationErrorCopyWithImpl(this._self, this._then);

  final ProblemValidationError _self;
  final $Res Function(ProblemValidationError) _then;

/// Create a copy of ProblemValidationError
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? field = null,Object? message = null,Object? code = freezed,}) {
  return _then(ProblemValidationError(
field: null == field ? _self.field : field // ignore: cast_nullable_to_non_nullable
as String,message: null == message ? _self.message : message // ignore: cast_nullable_to_non_nullable
as String,code: freezed == code ? _self.code : code // ignore: cast_nullable_to_non_nullable
as String?,
  ));
}

}


/// Adds pattern-matching-related methods to [ProblemValidationError].
extension ProblemValidationErrorPatterns on ProblemValidationError {
/// A variant of `map` that fallback to returning `orElse`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeMap<TResult extends Object?>(TResult Function( _ProblemValidationError value)?  $default,{required TResult orElse(),}){
final _that = this;
switch (_that) {
case _ProblemValidationError() when $default != null:
return $default(_that);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// Callbacks receives the raw object, upcasted.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case final Subclass2 value:
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult map<TResult extends Object?>(TResult Function( _ProblemValidationError value)  $default,){
final _that = this;
switch (_that) {
case _ProblemValidationError():
return $default(_that);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `map` that fallback to returning `null`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? mapOrNull<TResult extends Object?>(TResult? Function( _ProblemValidationError value)?  $default,){
final _that = this;
switch (_that) {
case _ProblemValidationError() when $default != null:
return $default(_that);case _:
  return null;

}
}
/// A variant of `when` that fallback to an `orElse` callback.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeWhen<TResult extends Object?>(TResult Function( String field,  String message,  String? code)?  $default,{required TResult orElse(),}) {final _that = this;
switch (_that) {
case _ProblemValidationError() when $default != null:
return $default(_that.field,_that.message,_that.code);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// As opposed to `map`, this offers destructuring.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case Subclass2(:final field2):
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult when<TResult extends Object?>(TResult Function( String field,  String message,  String? code)  $default,) {final _that = this;
switch (_that) {
case _ProblemValidationError():
return $default(_that.field,_that.message,_that.code);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `when` that fallback to returning `null`
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? whenOrNull<TResult extends Object?>(TResult? Function( String field,  String message,  String? code)?  $default,) {final _that = this;
switch (_that) {
case _ProblemValidationError() when $default != null:
return $default(_that.field,_that.message,_that.code);case _:
  return null;

}
}

}

/// @nodoc


class _ProblemValidationError extends ProblemValidationError {
  const _ProblemValidationError({required this.field, required this.message, this.code}): super._();
  

@override final  String field;
@override final  String message;
@override final  String? code;

/// Create a copy of ProblemValidationError
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$ProblemValidationErrorCopyWith<_ProblemValidationError> get copyWith => __$ProblemValidationErrorCopyWithImpl<_ProblemValidationError>(this, _$identity);



@override
bool operator ==(Object other) {
    return identical(this, other) || (other.runtimeType == runtimeType&&other is _ProblemValidationError&&(identical(other.field, field) || other.field == field)&&(identical(other.message, message) || other.message == message)&&(identical(other.code, code) || other.code == code));
}


@override
int get hashCode {
    return Object.hash(runtimeType,field,message,code);
}

@override
String toString() {
    return 'ProblemValidationError(field: $field, message: $message, code: $code)';
}


}

/// @nodoc
abstract mixin class _$ProblemValidationErrorCopyWith<$Res> implements $ProblemValidationErrorCopyWith<$Res> {
  factory _$ProblemValidationErrorCopyWith(_ProblemValidationError value, $Res Function(_ProblemValidationError) _then) = __$ProblemValidationErrorCopyWithImpl;
@override @useResult
$Res call({
 String field, String message, String? code
});




}
/// @nodoc
class __$ProblemValidationErrorCopyWithImpl<$Res>
    implements _$ProblemValidationErrorCopyWith<$Res> {
  __$ProblemValidationErrorCopyWithImpl(this._self, this._then);

  final _ProblemValidationError _self;
  final $Res Function(_ProblemValidationError) _then;

/// Create a copy of ProblemValidationError
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? field = null,Object? message = null,Object? code = freezed,}) {
  return _then(_ProblemValidationError(
field: null == field ? _self.field : field // ignore: cast_nullable_to_non_nullable
as String,message: null == message ? _self.message : message // ignore: cast_nullable_to_non_nullable
as String,code: freezed == code ? _self.code : code // ignore: cast_nullable_to_non_nullable
as String?,
  ));
}


}

// dart format on
