import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'problem_detail.freezed.dart';

/// Represents an RFC 9457 Problem Detail error response from the backend.
@freezed
abstract class ProblemDetail with _$ProblemDetail {
  const ProblemDetail._();

  /// Creates a Problem Detail instance.
  const factory ProblemDetail({
    /// A short, human-readable summary of the problem type.
    required String title,

    /// The HTTP status code generated by the origin server for this occurrence.
    required int status,

    /// A URI reference that identifies the problem type.
    String? type,

    /// A human-readable explanation specific to this occurrence of the problem.
    @Default('') String detail,

    /// A URI reference that identifies the specific occurrence of the problem.
    String? instance,

    /// A stable, machine-readable error code (e.g. `RESOURCE_NOT_FOUND`, `VALIDATION_FAILED`).
    String? code,

    /// A unique trace/correlation identifier for support.
    String? traceId,

    /// Optional list of field-specific validation errors.
    @Default([]) List<ProblemValidationError> errors,
  }) = _ProblemDetail;

  /// Returns the best human-readable message to display in the UI.
  String get displayMessage {
    if (detail.isNotEmpty) {
      return detail;
    }
    return title;
  }

  /// Returns `true` if this problem represents an input or validation warning (400, 409, or VALIDATION_FAILED).
  bool get isValidationError =>
      status == 400 ||
      status == 409 ||
      code == 'VALIDATION_FAILED' ||
      code == 'INVALID_VALUE' ||
      errors.isNotEmpty;

  /// Creates a [ProblemDetail] from a JSON map, tolerating missing or malformed RFC 9457 fields.
  factory ProblemDetail.fromJson(Map<String, dynamic> json) {
    final rawErrors = json['errors'];
    final parsedErrors = <ProblemValidationError>[];

    if (rawErrors is List) {
      for (final e in rawErrors) {
        if (e is Map<String, dynamic>) {
          parsedErrors.add(ProblemValidationError.fromJson(e));
        }
      }
    }

    return ProblemDetail(
      type: json['type'] as String?,
      title: (json['title'] as String?) ?? 'Error',
      status: (json['status'] as num?)?.toInt() ?? 500,
      detail: (json['detail'] as String?) ?? '',
      instance: json['instance'] as String?,
      code: json['code'] as String?,
      traceId: json['traceId'] as String?,
      errors: List.unmodifiable(parsedErrors),
    );
  }

  Map<String, dynamic> toJson() => {
    if (type != null) 'type': type,
    'title': title,
    'status': status,
    if (detail.isNotEmpty) 'detail': detail,
    if (instance != null) 'instance': instance,
    if (code != null) 'code': code,
    if (traceId != null) 'traceId': traceId,
    if (errors.isNotEmpty) 'errors': errors.map((e) => e.toJson()).toList(),
  };

  /// Parses a [ProblemDetail] from a [DioException].
  ///
  /// If the backend returned an RFC 9457 JSON body, it is parsed directly.
  /// Otherwise, a fallback [ProblemDetail] is created based on the Dio error type.
  factory ProblemDetail.fromDioException(DioException dioException) {
    final responseData = dioException.response?.data;

    if (responseData is Map<String, dynamic>) {
      try {
        return ProblemDetail.fromJson(responseData);
      } catch (_) {
        // Fall back to Dio error info if JSON didn't match
      }
    } else if (responseData is String && responseData.trim().startsWith('{')) {
      try {
        final decoded = jsonDecode(responseData);
        if (decoded is Map<String, dynamic>) {
          return ProblemDetail.fromJson(decoded);
        }
      } catch (_) {
        // Fall back
      }
    }

    // Network / timeout fallbacks
    switch (dioException.type) {
      case DioExceptionType.connectionTimeout:
      case DioExceptionType.sendTimeout:
      case DioExceptionType.receiveTimeout:
        return const ProblemDetail(
          title: 'Connection Timeout',
          status: 408,
          detail: 'The request timed out. Please check your connection.',
          code: 'CONNECTION_TIMEOUT',
        );

      case DioExceptionType.connectionError:
        return const ProblemDetail(
          title: 'Connection Error',
          status: 503,
          detail: 'Unable to connect to the server. Please check your network or server status.',
          code: 'CONNECTION_ERROR',
        );

      default:
        final statusCode = dioException.response?.statusCode ?? 500;
        final message = dioException.message ?? 'An unexpected error occurred.';
        return ProblemDetail(
          title: 'Error ($statusCode)',
          status: statusCode,
          detail: message,
          code: 'UNKNOWN_ERROR',
        );
    }
  }
}

/// Represents an individual field validation error in RFC 9457 responses.
@freezed
abstract class ProblemValidationError with _$ProblemValidationError {
  const ProblemValidationError._();

  /// Creates a Problem Validation Error instance.
  const factory ProblemValidationError({
    required String field,
    required String message,
    String? code,
  }) = _ProblemValidationError;

  factory ProblemValidationError.fromJson(Map<String, dynamic> json) {
    return ProblemValidationError(
      field: (json['field'] as String?) ?? '',
      code: json['code'] as String?,
      message: (json['message'] as String?) ?? '',
    );
  }

  Map<String, dynamic> toJson() => {
    'field': field,
    if (code != null) 'code': code,
    'message': message,
  };
}
