name: CI

on:
  push:
    branches:
      - feature/migration
    tags:
      - '*'
  workflow_dispatch:


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Run Flutter doctor
        run: flutter doctor

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href /

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OneLiteFeather Harbor
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          registry: harbor.onelitefeather.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: harbor.onelitefeather.dev/stelaris/stelaris-ui:${{ github.ref_name }},harbor.onelitefeather.dev/stelaris/stelaris-ui:latest