name: CI

on:
  push:
    branches:
      - feature/migration
    tags:
      - '*'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OneLiteFeather Harbor
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          registry: ${{ secrets.HARBOR_REGISTRY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/stelaris/stelaris-ui:${{ github.ref_name | replace(':', '-') | replace('/', '-') }},${{ secrets.HARBOR_REGISTRY }}/stelaris/stelaris-ui:latest